**Need df for combined articles and twitter aggregated by month**

In [1]:
import pandas as pd 
import numpy as np
Art=pd.read_csv('../data/raw/Aggregated_California_Env_Articles_Tweets.csv')
Art.head()

,year_month,article_count,rate_per_100k,mean_title_sentiment,mean_title_risk,mean_body_risk,avg_sentiment,avg_risk,mean_body_sentiment,tweet_count,...,mean_body_risk_lag1,mean_title_sentiment_lag1,mean_body_sentiment_lag1,FIRE_Acres_Burned_lag1,tweet_count_lag1,avg_risk_lag1,avg_sentiment_lag1,avg_likes_lag1,log_rate,logdiff_rate
0,2011-02,1.0,0.715017,0.028871,0.000000,0.015097,-0.465573,0.047619,-0.273456,6,...,0.018939,-0.484032,0.004761,62.42,0.0,0.021802,-0.185547,7.516662,0.539423,-0.240634
1,2011-03,1.0,0.821057,0.021148,0.000000,0.005263,-0.012873,0.000000,0.198157,5,...,0.015097,0.028871,-0.273456,35.53,6.0,0.047619,-0.465573,0.000000,0.599417,0.059994
2,2011-04,0.0,0.833176,-0.125413,0.036783,0.020489,-0.185547,0.021802,-0.167308,0,...,0.005263,0.021148,0.198157,3770.74,5.0,0.000000,-0.012873,1.000000,0.606050,0.006633
3,2011-05,0.0,0.875592,-0.125413,0.036783,0.020489,-0.185547,0.021802,-0.167308,0,...,0.020489,-0.125413,-0.167308,146.96,0.0,0.021802,-0.185547,7.516662,0.628925,0.022874
4,2011-06,0.0,0.969514,-0.125413,0.036783,0.020489,-0.185547,0.021802,-0.167308,0,...,0.020489,-0.125413,-0.167308,3941.78,0.0,0.021802,-0.185547,7.516662,0.677787,0.048862

In [2]:
Art.columns

Art['year_month'] = (
    pd.to_datetime(Art['year_month'])
    .dt.to_period('M')
)

In [3]:
Art1=Art[['year_month', 'article_count', 'rate_per_100k', 'mean_title_sentiment',
       'mean_title_risk', 'mean_body_risk', 'avg_sentiment', 'avg_risk',
       'mean_body_sentiment', 'tweet_count','avg_likes']]
Art1.head()
Art[['year_month']].dtypes

# Art1.to_csv('Media_with_features.csv', index=False)

year_month    period[M]
dtype: object

In [4]:
All= pd.read_csv('../data/interim/all_counties_processed_no_fire_2006_2024.csv')
All.head()

,County,Year-Month,Precipitation,Avg Rel Hum (%),Avg Wind Speed (mph),Wind Run (miles),windeventcount,Avg Soil Temp (F),AQI_PM25,AQI_PM10,FIRE_Acres_Burned,fungicide_lbs_prd_used,rodent_lbs_prd_used,rate_per_100k,log1p_rate_per_100k
0,Fresno,2006-08,0.000000,48.903226,4.540860,3378.950000,0.000000,75.205914,56.0,37.0,0.00,112982.8908,156775.7542,10.182585,2.414358
1,Fresno,2006-09,0.001667,46.972222,4.318333,3109.000000,0.000000,71.270000,62.0,58.0,0.00,80525.2145,18115.5357,6.675250,2.038001
2,Fresno,2006-10,0.370000,57.645161,3.672043,2732.816667,0.166667,63.884946,62.0,35.0,163.87,21487.1846,15512.5572,5.430712,1.861085
3,Fresno,2006-11,0.378333,72.927778,3.873889,2785.400000,0.166667,58.401111,88.0,44.5,42.80,6044.5023,9845.2947,6.109551,1.961439
4,Fresno,2006-12,0.768333,72.549283,4.126487,3047.033333,1.166667,49.833129,100.5,50.5,50.55,11001.3873,71.9232,4.978153,1.788112

In [5]:
All=All[['County','Year-Month','rate_per_100k']]
Art=Art[['year_month','article_count','mean_title_sentiment',
       'mean_title_risk', 'mean_body_risk', 'avg_sentiment', 'avg_risk',
       'mean_body_sentiment', 'tweet_count','avg_likes']]
All.head()

   County Year-Month  rate_per_100k
0  Fresno    2006-08      10.182585
1  Fresno    2006-09       6.675250
2  Fresno    2006-10       5.430712
3  Fresno    2006-11       6.109551
4  Fresno    2006-12       4.978153

In [6]:
# County_features= All.merge(Art, how='left',left_on='Year-Month',right_on='year_month')

In [7]:
# CF2011= County_features.loc[County_features['Year-Month']>='2011-01']
# CF2011.head()

In [8]:
Sentiment=pd.read_csv('../data/raw/articlewise_nlp_features.csv')
Counties=pd.read_csv('../data/raw/vf_clean_normal.csv')
Tweets=pd.read_csv('../data/raw/twitter_likes_clusters_sentiment')

In [9]:
Sentiment.head()
#Sentiment.columns

,year_month,query_term,title,published,link,source,summary,real_url,article_text,article_detail,...,title_score,body_label,body_positive,body_neutral,body_negative,body_sentiment,title_risk,body_risk,date,month
0,2001-12,"""valley fever""",HEALTH | Valley fever hits UK patient - BBC,"Sat, 15 Dec 2001 08:00:00 GMT",https://news.google.com/rss/articles/CBMiWEFVX...,BBC,"<a href=""https://news.google.com/rss/articles/...",http://news.bbc.co.uk/2/hi/health/1709617.stm,he developed a particularly nasty pneumonia an...,He developed a particularly nasty pneumonia an...,...,NaN,negative,0.015520,0.348735,0.635745,-0.620226,0.000000,0.031519,2001-12-01,2001-12
1,2004-05,"""valley fever""","40 years later, Mills still overcoming adversi...","Fri, 21 May 2004 07:00:00 GMT",https://news.google.com/rss/articles/CBMimgFBV...,The Spokesman-Review,"<a href=""https://news.google.com/rss/articles/...",https://www.spokesman.com/stories/2004/may/21/...,NaN,"RAPID CITY, S.D. — Forty years after becoming ...",...,NaN,positive,0.599006,0.393072,0.007922,0.591084,0.000000,0.007421,2004-05-01,2004-05
2,2007-09,"""valley fever""",Frederick Ragsdale Obituary (2007) - San Luis ...,"Sun, 16 Sep 2007 07:00:00 GMT",https://news.google.com/rss/articles/CBMimwFBV...,Legacy obituary,"<a href=""https://news.google.com/rss/articles/...",https://www.legacy.com/us/obituaries/sanluisob...,NaN,"Frederick F. Ragsdale, M.D., 98, of Paso Roble...",...,NaN,neutral,0.062902,0.867127,0.069971,-0.007069,0.000000,0.003717,2007-09-01,2007-09
3,2007-12,"""valley fever""",Infection Hits a California Prison Hard (Publi...,"Sun, 30 Dec 2007 08:00:00 GMT",https://news.google.com/rss/articles/CBMiYkFVX...,The New York Times,"<a href=""https://news.google.com/rss/articles/...",https://www.nytimes.com/2007/12/30/us/30inmate...,NaN,"COALINGA, Calif.  When any of the 5,300 inmat...",...,NaN,negative,0.014893,0.445832,0.539275,-0.524382,0.090909,0.044037,2007-12-01,2007-12
4,2009-02,coccidioidomycosis,"Increase in Coccidioidomycosis --- California,...","Fri, 13 Feb 2009 08:00:00 GMT",https://news.google.com/rss/articles/CBMiZEFVX...,Centers for Disease Control and Prevention | C...,"<a href=""https://news.google.com/rss/articles/...",https://www.cdc.gov/mmwr/preview/mmwrhtml/mm58...,coccidioidomycosis is an infection resulting f...,Coccidioidomycosis is an infection resulting f...,...,NaN,neutral,0.029749,0.744514,0.225737,-0.195988,0.083333,0.067118,2009-02-01,2009-02

In [10]:
counties = ['Alameda',    'Contra Costa',          'Fresno',            'Kern',
     'Los Angeles',          'Merced',        'Monterey',          'Orange',
     'Riverside',      'Sacramento',  'San Bernardino',       'San Diego',
     'San Joaquin', 'San Luis Obispo',       'San Mateo',   'Santa Barbara',
     'Santa Clara',          'Solano',      'Stanislaus',          'Tulare',
     'Ventura','Arizona','New Mexico','Nevada','Utah', 'California']

def find_counties(text):
    if pd.isna(text):
        return ['Other']
    text = text.lower()
    found = [
        county
        for county in counties
        if county.lower() in text
    ]
    return found if found else ['Other']

Sentiment["County"] = Sentiment["article_detail"].apply(find_counties)

Sentiment['County'] = Sentiment['County'].apply(
    lambda x: ast.literal_eval(x) if isinstance(x, str) else x
    #Converts County column from strings ''['county','county','county']'' to list 
)

In [11]:
Counties.head()

    County Year-Month  num_cases  population  rate_per_100k
0  Alameda    2001-01        0.0   1469484.0       0.000000
1  Alameda    2001-02        0.0   1469484.0       0.000000
2  Alameda    2001-03        2.0   1469484.0       0.136102
3  Alameda    2001-04        2.0   1469484.0       0.136102
4  Alameda    2001-05        0.0   1469484.0       0.000000

In [12]:
Tweets.head()

,month,min_sentiment,max_sentiment,avg_sentiment,avg_positive,avg_negative,min_risk,max_risk,avg_risk,month.1,tweet_count,avg_likes,total_likes,Cluster_0,Cluster_1,Cluster_2,Cluster_3,Cluster_4
0,2011-01-01,-0.855221,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,2011-01-01,0,7.516662,0,0,0,0,0,0
1,2011-02-01,-0.835635,-0.155300,-0.465573,0.019396,0.484968,0.000000,0.285714,0.047619,2011-02-01,6,0.000000,0,0,2,0,3,1
2,2011-03-01,-0.023465,-0.000769,-0.012873,0.024719,0.037591,0.000000,0.000000,0.000000,2011-03-01,5,1.000000,5,0,0,0,5,0
3,2011-04-01,-0.855221,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,2011-04-01,0,7.516662,0,0,0,0,0,0
4,2011-05-01,-0.855221,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,2011-05-01,0,7.516662,0,0,0,0,0,0

In [13]:
Tweets['year_month']= (
    pd.to_datetime(Tweets['month'])
    .dt.to_period('M')
)

Sentiment['year_month']= (
    pd.to_datetime(Sentiment['year_month'])
    .dt.to_period('M')
)

Counties['year_month']=(
    pd.to_datetime(Counties['Year-Month'])
    .dt.to_period('M')
)

In [254]:
Tweets=Tweets[['year_month','min_sentiment','max_sentiment','avg_sentiment',
               'avg_positive','avg_negative','min_risk','max_risk',
               'avg_risk','tweet_count','avg_likes','total_likes']]

Counties= Counties[['County','year_month','num_cases','rate_per_100k']]

Sentiment=Sentiment[[
       'year_month','title_label', 'title_positive', 
       'title_neutral', 'title_negative','title_sentiment',
       'body_label', 'body_positive','body_neutral', 'body_negative', 
       'body_sentiment', 'title_risk','body_risk'
       ]]

In [255]:
Counties= Counties.loc[Counties['year_month']>='2011-01']

Tweets= Tweets.loc[Tweets['year_month']>='2011-01']

Sentiment=Sentiment.loc[Sentiment['year_month']>='2011-01']

In [256]:
Sentiment.head()

,year_month,title_label,title_positive,title_neutral,title_negative,title_sentiment,body_label,body_positive,body_neutral,body_negative,body_sentiment,title_risk,body_risk
9,2011-01,neutral,0.046798,0.935427,0.017774,0.029024,negative,0.027698,0.462833,0.509469,-0.481771,0.000000,0.013675
10,2011-01,negative,0.014129,0.487710,0.498161,-0.484032,neutral,0.059797,0.885166,0.055036,0.004761,0.142857,0.018939
11,2011-02,neutral,0.054337,0.920198,0.025465,0.028871,neutral,0.026638,0.673269,0.300094,-0.273456,0.000000,0.015097
12,2011-03,neutral,0.032024,0.957100,0.010876,0.021148,neutral,0.257153,0.683851,0.058996,0.198157,0.000000,0.005263
13,2011-07,negative,0.011374,0.272729,0.715897,-0.704523,negative,0.014198,0.384866,0.600936,-0.586739,0.000000,0.004630

In [257]:
Counties.head()

      County year_month  num_cases  rate_per_100k
120  Alameda    2011-01        4.0       0.260930
121  Alameda    2011-02        3.0       0.195697
122  Alameda    2011-03        4.0       0.260930
123  Alameda    2011-04        1.0       0.065232
124  Alameda    2011-05        0.0       0.000000

In [258]:
Counties = Counties.sort_values(['County', 'year_month'])

In [259]:
len(Counties)
Counties.head()
Counties.loc[Counties['County']=='Alameda']

      County year_month  num_cases  rate_per_100k
120  Alameda    2011-01        4.0       0.260930
121  Alameda    2011-02        3.0       0.195697
122  Alameda    2011-03        4.0       0.260930
123  Alameda    2011-04        1.0       0.065232
124  Alameda    2011-05        0.0       0.000000
..       ...        ...        ...            ...
283  Alameda    2024-08       13.0       0.782448
284  Alameda    2024-09        7.0       0.421318
285  Alameda    2024-10       13.0       0.782448
286  Alameda    2024-11       17.0       1.023201
287  Alameda    2024-12       11.0       0.662071

[168 rows x 4 columns]

In [260]:
Sentiment.columns

Index(['year_month', 'title_label', 'title_positive', 'title_neutral',
       'title_negative', 'title_sentiment', 'body_label', 'body_positive',
       'body_neutral', 'body_negative', 'body_sentiment', 'title_risk',
       'body_risk'],
      dtype='str')

In [261]:
monthly_sentiment = (
    Sentiment.groupby('year_month')
    .agg(
        mean_title_positive=('title_positive','mean'),
        mean_title_neutral=('title_neutral','mean'),
        mean_title_negative=('title_negative','mean'),
        mean_title_sentiment=('title_sentiment', 'mean'),
        mean_body_positive=('body_positive','mean'),
        mean_body_neutral=('body_neutral','mean'),
        mean_body_negative=('body_negative','mean'),
        mean_title_risk=('title_risk', 'mean'),
        mean_body_sentiment=('body_sentiment', 'mean'),
        mean_body_risk=('body_risk', 'mean'),
        article_count=('year_month', 'size')
    )
    .reset_index()
)

In [262]:
Sentiment.head()

,year_month,title_label,title_positive,title_neutral,title_negative,title_sentiment,body_label,body_positive,body_neutral,body_negative,body_sentiment,title_risk,body_risk
9,2011-01,neutral,0.046798,0.935427,0.017774,0.029024,negative,0.027698,0.462833,0.509469,-0.481771,0.000000,0.013675
10,2011-01,negative,0.014129,0.487710,0.498161,-0.484032,neutral,0.059797,0.885166,0.055036,0.004761,0.142857,0.018939
11,2011-02,neutral,0.054337,0.920198,0.025465,0.028871,neutral,0.026638,0.673269,0.300094,-0.273456,0.000000,0.015097
12,2011-03,neutral,0.032024,0.957100,0.010876,0.021148,neutral,0.257153,0.683851,0.058996,0.198157,0.000000,0.005263
13,2011-07,negative,0.011374,0.272729,0.715897,-0.704523,negative,0.014198,0.384866,0.600936,-0.586739,0.000000,0.004630

In [263]:
monthly_sentiment.head()

,year_month,mean_title_positive,mean_title_neutral,mean_title_negative,mean_title_sentiment,mean_body_positive,mean_body_neutral,mean_body_negative,mean_title_risk,mean_body_sentiment,mean_body_risk,article_count
0,2011-01,0.030464,0.711569,0.257968,-0.227504,0.043748,0.673999,0.282253,0.071429,-0.238505,0.016307,2
1,2011-02,0.054337,0.920198,0.025465,0.028871,0.026638,0.673269,0.300094,0.000000,-0.273456,0.015097,1
2,2011-03,0.032024,0.957100,0.010876,0.021148,0.257153,0.683851,0.058996,0.000000,0.198157,0.005263,1
3,2011-07,0.011374,0.272729,0.715897,-0.704523,0.014198,0.384866,0.600936,0.000000,-0.586739,0.004630,2
4,2011-08,0.020025,0.687142,0.292833,-0.272808,0.021326,0.348721,0.629953,0.000000,-0.608628,0.003304,1

In [264]:
monthly_sentiment[monthly_sentiment.isna().any(axis=1)]

,year_month,mean_title_positive,mean_title_neutral,mean_title_negative,mean_title_sentiment,mean_body_positive,mean_body_neutral,mean_body_negative,mean_title_risk,mean_body_sentiment,mean_body_risk,article_count
49,2015-12,0.326187,0.664022,0.009791,0.316396,NaN,NaN,NaN,0.0,NaN,NaN,1

In [265]:
monthly_sentiment.columns

Index(['year_month', 'mean_title_positive', 'mean_title_neutral',
       'mean_title_negative', 'mean_title_sentiment', 'mean_body_positive',
       'mean_body_neutral', 'mean_body_negative', 'mean_title_risk',
       'mean_body_sentiment', 'mean_body_risk', 'article_count'],
      dtype='str')

In [267]:
MonthlyMedia = monthly_sentiment.sort_values('year_month').copy()

body_cols = [
    'mean_title_positive', 'mean_title_neutral',
       'mean_title_negative', 'mean_title_sentiment', 'mean_body_positive',
       'mean_body_neutral', 'mean_body_negative', 'mean_title_risk',
       'mean_body_sentiment', 'mean_body_risk', 'article_count'
]

for col in body_cols:
    past_mean = MonthlyMedia[col].shift(1).expanding(min_periods=1).mean()
    MonthlyMedia[col] = MonthlyMedia[col].fillna(past_mean)

In [268]:
MonthlyMedia.loc[MonthlyMedia['year_month']=='2015-12']

,year_month,mean_title_positive,mean_title_neutral,mean_title_negative,mean_title_sentiment,mean_body_positive,mean_body_neutral,mean_body_negative,mean_title_risk,mean_body_sentiment,mean_body_risk,article_count
49,2015-12,0.326187,0.664022,0.009791,0.316396,0.100693,0.619644,0.279663,0.0,-0.178969,0.019125,1

In [269]:
monthly_sentiment.loc[monthly_sentiment['year_month']=='2015-12']

,year_month,mean_title_positive,mean_title_neutral,mean_title_negative,mean_title_sentiment,mean_body_positive,mean_body_neutral,mean_body_negative,mean_title_risk,mean_body_sentiment,mean_body_risk,article_count
49,2015-12,0.326187,0.664022,0.009791,0.316396,NaN,NaN,NaN,0.0,NaN,NaN,1

In [ ]:
Tweets.head()

,year_month,min_sentiment,max_sentiment,avg_sentiment,avg_positive,avg_negative,min_risk,max_risk,avg_risk,tweet_count,avg_likes,total_likes
0,2011-01,-0.855221,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,0,7.516662,0
1,2011-02,-0.835635,-0.155300,-0.465573,0.019396,0.484968,0.000000,0.285714,0.047619,6,0.000000,0
2,2011-03,-0.023465,-0.000769,-0.012873,0.024719,0.037591,0.000000,0.000000,0.000000,5,1.000000,5
3,2011-04,-0.855221,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,0,7.516662,0
4,2011-05,-0.855221,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,0,7.516662,0

In [273]:
Media=MonthlyMedia.merge(Tweets, how='left', on='year_month')

In [274]:
Media.head()

,year_month,mean_title_positive,mean_title_neutral,mean_title_negative,mean_title_sentiment,mean_body_positive,mean_body_neutral,mean_body_negative,mean_title_risk,mean_body_sentiment,...,max_sentiment,avg_sentiment,avg_positive,avg_negative,min_risk,max_risk,avg_risk,tweet_count,avg_likes,total_likes
0,2011-01,0.030464,0.711569,0.257968,-0.227504,0.043748,0.673999,0.282253,0.071429,-0.238505,...,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,0,7.516662,0
1,2011-02,0.054337,0.920198,0.025465,0.028871,0.026638,0.673269,0.300094,0.000000,-0.273456,...,-0.155300,-0.465573,0.019396,0.484968,0.000000,0.285714,0.047619,6,0.000000,0
2,2011-03,0.032024,0.957100,0.010876,0.021148,0.257153,0.683851,0.058996,0.000000,0.198157,...,-0.000769,-0.012873,0.024719,0.037591,0.000000,0.000000,0.000000,5,1.000000,5
3,2011-07,0.011374,0.272729,0.715897,-0.704523,0.014198,0.384866,0.600936,0.000000,-0.586739,...,0.899319,-0.170241,0.090889,0.261130,0.000000,0.285714,0.072980,15,0.533333,8
4,2011-08,0.020025,0.687142,0.292833,-0.272808,0.021326,0.348721,0.629953,0.000000,-0.608628,...,0.001636,-0.251575,0.035442,0.287017,0.000000,0.000000,0.000000,4,0.000000,0

In [275]:
Media[Media.isna().any(axis=1)]

Empty DataFrame
Columns: [year_month, mean_title_positive, mean_title_neutral, mean_title_negative, mean_title_sentiment, mean_body_positive, mean_body_neutral, mean_body_negative, mean_title_risk, mean_body_sentiment, mean_body_risk, article_count, min_sentiment, max_sentiment, avg_sentiment, avg_positive, avg_negative, min_risk, max_risk, avg_risk, tweet_count, avg_likes, total_likes]
Index: []

[0 rows x 23 columns]

In [281]:
County_media= Counties.merge(Media, on='year_month', how='inner')

In [282]:
County_media

,County,year_month,num_cases,rate_per_100k,mean_title_positive,mean_title_neutral,mean_title_negative,mean_title_sentiment,mean_body_positive,mean_body_neutral,...,max_sentiment,avg_sentiment,avg_positive,avg_negative,min_risk,max_risk,avg_risk,tweet_count,avg_likes,total_likes
0,Alameda,2011-01,4.0,0.260930,0.030464,0.711569,0.257968,-0.227504,0.043748,0.673999,...,0.760856,-0.185547,0.170390,0.355937,0.001406,0.160961,0.021802,0,7.516662,0
1,Alameda,2011-02,3.0,0.195697,0.054337,0.920198,0.025465,0.028871,0.026638,0.673269,...,-0.155300,-0.465573,0.019396,0.484968,0.000000,0.285714,0.047619,6,0.000000,0
2,Alameda,2011-03,4.0,0.260930,0.032024,0.957100,0.010876,0.021148,0.257153,0.683851,...,-0.000769,-0.012873,0.024719,0.037591,0.000000,0.000000,0.000000,5,1.000000,5
3,Alameda,2011-07,2.0,0.130465,0.011374,0.272729,0.715897,-0.704523,0.014198,0.384866,...,0.899319,-0.170241,0.090889,0.261130,0.000000,0.285714,0.072980,15,0.533333,8
4,Alameda,2011-08,0.0,0.000000,0.020025,0.687142,0.292833,-0.272808,0.021326,0.348721,...,0.001636,-0.251575,0.035442,0.287017,0.000000,0.000000,0.000000,4,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3271,Ventura,2024-08,22.0,2.655587,0.073822,0.563461,0.362717,-0.288895,0.035995,0.615236,...,0.327135,-0.257489,0.166392,0.423881,0.000000,0.040000,0.008000,5,5.200000,26
3272,Ventura,2024-09,22.0,2.655587,0.033320,0.744384,0.222296,-0.188976,0.048465,0.659364,...,0.599092,-0.389060,0.054322,0.443382,0.000000,0.266667,0.046625,79,9.088608,718
3273,Ventura,2024-10,30.0,3.621255,0.113773,0.724691,0.161536,-0.047762,0.066831,0.648239,...,0.879072,-0.214284,0.174417,0.388701,0.000000,0.200000,0.019336,33,13.909091,459
3274,Ventura,2024-11,45.0,5.431883,0.088194,0.769756,0.142050,-0.053856,0.153878,0.616024,...,0.964312,-0.195193,0.163813,0.359005,0.000000,0.055556,0.011013,14,10.857143,152
3275,Ventura,2024-12,41.0,4.949049,0.146872,0.570861,0.282268,-0.135396,0.114219,0.677176,...,0.970082,-0.375388,0.173904,0.549292,0.000000,0.070175,0.006341,25,43.200000,1080

In [284]:
County_media.to_csv('Media_per_county.csv', index=False)
Media.to_csv('Media_features.csv', index=False)
MonthlyMedia.to_csv('Article_features.csv', index=False)